package com.hospital.appointmentservice.mapper;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.factory.Mappers;

import com.hospital.appointmentservice.dto.AppointmentRequest;
import com.hospital.appointmentservice.dto.AppointmentResponse;
import com.hospital.appointmentservice.model.Appointment;

/**
 * Appointment Mapper
 * 
 * MapStruct-based mapper for converting between Appointment entities and DTOs.
 * This mapper handles the object transformation between different layers of the application:
 * - Converts AppointmentRequest DTO to Appointment entity for database operations
 * - Converts Appointment entity to AppointmentResponse DTO for API responses
 * 
 * Key Features:
 * - Uses MapStruct for compile-time code generation (no runtime reflection)
 * - Spring component model for dependency injection
 * - Custom mapping configurations for field transformations
 * - Default values and constant mappings for business logic
 * 
 * Mapping Rules:
 * - When converting Request → Entity: ID, createdAt, updatedAt are ignored (set by database)
 * - When converting Request → Entity: Status defaults to "SCHEDULED"
 * - When converting Entity → Response: All fields are mapped by name convention
 * 
 * @author Hospital Management System
 * @version 1.0
 */
@Mapper(componentModel = "spring")
public interface AppointmentMapper {
    
    /**
     * Singleton instance of the mapper for manual usage.
     * Note: In Spring applications, prefer dependency injection over this instance.
     */
    AppointmentMapper INSTANCE = Mappers.getMapper(AppointmentMapper.class);
    
    /**
     * Converts an AppointmentRequest DTO to an Appointment entity.
     * 
     * This method is used when creating a new appointment from API request data.
     * Mapping configurations:
     * - `id`: Ignored (will be generated by database)
     * - `status`: Set to constant "SCHEDULED" (default status for new appointments)
     * - `createdAt`, `updatedAt`: Ignored (set by entity lifecycle callbacks)
     * - All other fields: Mapped by name convention
     * 
     * @param request AppointmentRequest DTO containing appointment data from API
     * @return Appointment entity ready for database persistence
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "status", constant = "SCHEDULED")
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    Appointment toEntity(AppointmentRequest request);
    
    /**
     * Converts an Appointment entity to an AppointmentResponse DTO.
     * 
     * This method is used when returning appointment data in API responses.
     * All fields are mapped by name convention from entity to DTO.
     * 
     * @param appointment Appointment entity from database
     * @return AppointmentResponse DTO for API response
     */
    AppointmentResponse toResponse(Appointment appointment);
}
